bot:
  map: ston
buff_skill:
  cooldown:
  - 600
  - 300
  - 300
  keys:
  - '1'
  - a
  - x
channel_change:
  enable: true
  mode: 'true'
directional_attack:
  cooldown: 0.15
  range_x: 300
health_monitor:
  add_mp_percent: 10
key:
  add_hp: end
  add_mp: del
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - -1
monster_detect:
  search_box_margin: 80
system:
  fps_limit_keyboard_controller: 10
