bot:
  map: fire_land_1
buff_skill:
  cooldown:
  - 600
  keys:
  - '1'
channel_change:
  mode: 'true'
directional_attack:
  cooldown: 0.3
  range_x: 200
  range_y: 100
health_monitor:
  add_hp_percent: 20
key:
  add_hp: end
  add_mp: del
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - -1
