bot:
  map: land_of_wild_boar
buff_skill:
  cooldown:
  - 80
  - 110
  - 61
  - 600
  keys:
  - a
  - x
  - f
  - '1'
channel_change:
  mode: 'true'
directional_attack:
  cooldown: 0.3
  range_x: 250
health_monitor:
  add_hp_percent: 40
  add_mp_percent: 10
key:
  add_hp: end
  add_mp: del
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 1
  - 0
system:
  fps_limit_keyboard_controller: 10
  fps_limit_main: 30
