aoe_skill:
  range_x: 300
bot:
  attack: aoe_skill
  map: garden_of_green_2
buff_skill:
  cooldown:
  - 80
  - 110
  - 61
  - 600
  keys:
  - a
  - x
  - f
  - '1'
channel_change:
  enable: true
  mode: 'true'
directional_attack:
  cooldown: 0.15
  range_x: 300
health_monitor:
  add_hp_percent: 40
  add_mp_percent: 10
key:
  add_hp: end
  add_mp: del
  aoe_skill: z
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - 2
system:
  fps_limit_keyboard_controller: 10
  fps_limit_main: 30
