bot:
  map: pig_shores
channel_change:
  mode: 'true'
directional_attack:
  cooldown: 0.3
  range_x: 200
  range_y: 100
key:
  add_hp: end
  add_mp: del
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - -1
system:
  fps_limit_main: 30
