bot:
  map: land_of_wild_boar
buff_skill:
  cooldown:
  - 180
  keys:
  - '1'
channel_change:
  enable: true
  mode: 'true'
directional_attack:
  cooldown: 0.15
  range_x: 250
  range_y: 80
health_monitor:
  add_mp_percent: 3
key:
  add_hp: end
  add_mp: del
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - -1
system:
  fps_limit_main: 30
