aoe_skill:
  range_x: 300
bot:
  map: black_mountain
buff_skill:
  cooldown:
  - 600
  keys:
  - '1'
channel_change:
  mode: 'true'
directional_attack:
  cooldown: 0.15
  range_x: 200
  range_y: 100
health_monitor:
  add_hp_percent: 30
  add_mp_percent: 10
key:
  add_hp: end
  add_mp: del
  aoe_skill: z
  directional_attack: z
  jump: alt
  teleport: z
minimap:
  offset:
  - 0
  - -1
system:
  fps_limit_keyboard_controller: 10
